version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_environment
    tty: true
    volumes:
      - .:/home/devuser/workspace
    ports:
      - "3000:3000"    # Node.js apps
      - "8000:8000"    # Python apps (FastAPI, Django)
      - "5432:5432"    # Postgres
      - "3306:3306"    # MySQL
      - "6379:6379"    # Redis
    depends_on:
      - postgres
      - mysql
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mysqldata:
