name: CI - Build Dev Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Buildar Imagem Docker
        run: |
          docker build -t dev-environment .

      - name: Testar Execução do Container
        run: |
          docker run --rm dev-environment echo "Container pronto para desenvolvimento! 🚀"

